### ISSUE TITLE
配置文件优化

### ISSUE THREAD

**Issue by Jesse205** [nwdxlgzs/Debug-Web-Single-MusicPlayer#5]
- 方案1：删除 `attach.json`，改用功能相似的`player.config.js`，类似 FusionApp
- 方案2：没想好

**Comment by nwdxlgzs** [comment]
配置文件更多是为了给以后的后端留出接口，通讯配置文件和通讯一整个修改的js来说，json会更友好。正如截止目前未pr时attach.js内容一样，它预计请求xxx.xxx/api=xxx&mid=xxx获取配置信息。

**Comment by Jesse205** [comment]
或者，保留attach.json，也保留player.config.js，用户可以在player.config.js中自定义请求路径、是否解密以及解密过程等

**Comment by nwdxlgzs** [comment]
正如项目说明一样，播放器就是空壳，它并不是设计成支持列表播放等功能的播放器而只是一个单曲播放器（遇到好听的歌又懒得用AE做视频，直接用它录制一个视频），所以json已经是最好的了。不排除在播放器完成设计后基于此播放器做成支持列表的新项目，但是，现在不行。（Debug-Web-Single-MusicPlayer的Single）

**Comment by Jesse205** [comment]
不，我的意思是attach.json用来存放歌曲信息，player.config.js用来存放客户端配置信息。有需求的用户，比如加密需求，就可以直接修改player.config.js，而不需要翻阅源码。

**Comment by nwdxlgzs** [comment]
解密在audioplayer。如果一个人真就拿来即用而不看点粗略的代码，那么这个人多半是遇到问题甩给开发者当“项目经理”，有技术的人不会连这点东西都不会或者不愿意看的。
