### ISSUE TITLE
html的溢出问题

### ISSUE THREAD

**Issue by Jesse205** [nwdxlgzs/Debug-Web-Single-MusicPlayer#7]
要点：

1. 非必要不要使用` overflow: hidden;`，这样可能会掩盖一些问题
2. 使用 `100%`而非`100vw`

我来解决这个问题吧，音量条需要这个
![image](https://github.com/nwdxlgzs/Debug-Web-Single-MusicPlayer/assets/51242302/e3536369-419a-4b26-a51e-4c147cf95264)

**Comment by nwdxlgzs** [comment]
OK
